# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: configuration_update.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import robot_arm_pb2 as robot__arm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='configuration_update.proto',
  package='RobotArm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1a\x63onfiguration_update.proto\x12\x08RobotArm\x1a\x0frobot_arm.proto2\xd4\x01\n\x13\x43onfigurationUpdate\x12\x45\n\nSendUpdate\x12\x17.RobotArm.currentStatus\x1a\x1c.RobotArm.robotConfiguration\"\x00\x12:\n\x05Move5\x12\x16.RobotArm.moveRequest5\x1a\x17.RobotArm.currentStatus\"\x00\x12:\n\x05Move7\x12\x16.RobotArm.moveRequest7\x1a\x17.RobotArm.currentStatus\"\x00\x62\x06proto3'
  ,
  dependencies=[robot__arm__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CONFIGURATIONUPDATE = _descriptor.ServiceDescriptor(
  name='ConfigurationUpdate',
  full_name='RobotArm.ConfigurationUpdate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=58,
  serialized_end=270,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendUpdate',
    full_name='RobotArm.ConfigurationUpdate.SendUpdate',
    index=0,
    containing_service=None,
    input_type=robot__arm__pb2._CURRENTSTATUS,
    output_type=robot__arm__pb2._ROBOTCONFIGURATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Move5',
    full_name='RobotArm.ConfigurationUpdate.Move5',
    index=1,
    containing_service=None,
    input_type=robot__arm__pb2._MOVEREQUEST5,
    output_type=robot__arm__pb2._CURRENTSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Move7',
    full_name='RobotArm.ConfigurationUpdate.Move7',
    index=2,
    containing_service=None,
    input_type=robot__arm__pb2._MOVEREQUEST7,
    output_type=robot__arm__pb2._CURRENTSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONFIGURATIONUPDATE)

DESCRIPTOR.services_by_name['ConfigurationUpdate'] = _CONFIGURATIONUPDATE

# @@protoc_insertion_point(module_scope)
