# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dexter_update.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import robot_arm_pb2 as robot__arm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dexter_update.proto',
  package='SpotPlusArm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13\x64\x65xter_update.proto\x12\x0bSpotPlusArm\x1a\x0frobot_arm.proto2\xe1\x01\n\x0c\x44\x65xterUpdate\x12K\n\nSendUpdate\x12\x19.SpotPlusArm.dexterStatus\x1a .SpotPlusArm.dexterConfiguration\"\x00\x12\x41\n\x05Move5\x12\x1b.SpotPlusArm.dexterRequest5\x1a\x19.SpotPlusArm.dexterStatus\"\x00\x12\x41\n\x05Move7\x12\x1b.SpotPlusArm.dexterRequest7\x1a\x19.SpotPlusArm.dexterStatus\"\x00\x62\x06proto3'
  ,
  dependencies=[robot__arm__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DEXTERUPDATE = _descriptor.ServiceDescriptor(
  name='DexterUpdate',
  full_name='SpotPlusArm.DexterUpdate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=54,
  serialized_end=279,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendUpdate',
    full_name='SpotPlusArm.DexterUpdate.SendUpdate',
    index=0,
    containing_service=None,
    input_type=robot__arm__pb2._DEXTERSTATUS,
    output_type=robot__arm__pb2._DEXTERCONFIGURATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Move5',
    full_name='SpotPlusArm.DexterUpdate.Move5',
    index=1,
    containing_service=None,
    input_type=robot__arm__pb2._DEXTERREQUEST5,
    output_type=robot__arm__pb2._DEXTERSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Move7',
    full_name='SpotPlusArm.DexterUpdate.Move7',
    index=2,
    containing_service=None,
    input_type=robot__arm__pb2._DEXTERREQUEST7,
    output_type=robot__arm__pb2._DEXTERSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEXTERUPDATE)

DESCRIPTOR.services_by_name['DexterUpdate'] = _DEXTERUPDATE

# @@protoc_insertion_point(module_scope)
