# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_arm.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_arm.proto',
  package='RobotArm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0frobot_arm.proto\x12\x08RobotArm\"\xb6\x02\n\x12robotConfiguration\x12.\n\x02j1\x18\x01 \x01(\x0b\x32\".RobotArm.robotConfiguration.Joint\x12.\n\x02j2\x18\x02 \x01(\x0b\x32\".RobotArm.robotConfiguration.Joint\x12.\n\x02j3\x18\x03 \x01(\x0b\x32\".RobotArm.robotConfiguration.Joint\x12.\n\x02j4\x18\x04 \x01(\x0b\x32\".RobotArm.robotConfiguration.Joint\x12.\n\x02j5\x18\x05 \x01(\x0b\x32\".RobotArm.robotConfiguration.Joint\x1a\x30\n\x05Joint\x12\x14\n\x0c\x63urrentAngle\x18\x01 \x01(\x01\x12\x11\n\tgoalAngle\x18\x02 \x01(\x01\"s\n\x0cmoveRequest5\x12\n\n\x02j1\x18\x01 \x01(\x01\x12\n\n\x02j2\x18\x02 \x01(\x01\x12\n\n\x02j3\x18\x03 \x01(\x01\x12\n\n\x02j4\x18\x04 \x01(\x01\x12\n\n\x02j5\x18\x05 \x01(\x01\x12\'\n\x0b\x63ommandType\x18\x06 \x01(\x0e\x32\x12.RobotArm.MoveType\"\x8b\x01\n\x0cmoveRequest7\x12\n\n\x02j1\x18\x01 \x01(\x01\x12\n\n\x02j2\x18\x02 \x01(\x01\x12\n\n\x02j3\x18\x03 \x01(\x01\x12\n\n\x02j4\x18\x04 \x01(\x01\x12\n\n\x02j5\x18\x05 \x01(\x01\x12\n\n\x02j6\x18\x06 \x01(\x01\x12\n\n\x02j7\x18\x07 \x01(\x01\x12\'\n\x0b\x63ommandType\x18\x08 \x01(\x0e\x32\x12.RobotArm.MoveType\"\x1f\n\rcurrentStatus\x12\x0e\n\x06status\x18\x01 \x01(\x05*\"\n\x08MoveType\x12\n\n\x06P_MOVE\x10\x00\x12\n\n\x06\x41_MOVE\x10\x01\x62\x06proto3'
)

_MOVETYPE = _descriptor.EnumDescriptor(
  name='MoveType',
  full_name='RobotArm.MoveType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='P_MOVE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='A_MOVE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=634,
  serialized_end=668,
)
_sym_db.RegisterEnumDescriptor(_MOVETYPE)

MoveType = enum_type_wrapper.EnumTypeWrapper(_MOVETYPE)
P_MOVE = 0
A_MOVE = 1



_ROBOTCONFIGURATION_JOINT = _descriptor.Descriptor(
  name='Joint',
  full_name='RobotArm.robotConfiguration.Joint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentAngle', full_name='RobotArm.robotConfiguration.Joint.currentAngle', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goalAngle', full_name='RobotArm.robotConfiguration.Joint.goalAngle', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=340,
)

_ROBOTCONFIGURATION = _descriptor.Descriptor(
  name='robotConfiguration',
  full_name='RobotArm.robotConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='j1', full_name='RobotArm.robotConfiguration.j1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j2', full_name='RobotArm.robotConfiguration.j2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j3', full_name='RobotArm.robotConfiguration.j3', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j4', full_name='RobotArm.robotConfiguration.j4', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j5', full_name='RobotArm.robotConfiguration.j5', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ROBOTCONFIGURATION_JOINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=340,
)


_MOVEREQUEST5 = _descriptor.Descriptor(
  name='moveRequest5',
  full_name='RobotArm.moveRequest5',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='j1', full_name='RobotArm.moveRequest5.j1', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j2', full_name='RobotArm.moveRequest5.j2', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j3', full_name='RobotArm.moveRequest5.j3', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j4', full_name='RobotArm.moveRequest5.j4', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j5', full_name='RobotArm.moveRequest5.j5', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commandType', full_name='RobotArm.moveRequest5.commandType', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=457,
)


_MOVEREQUEST7 = _descriptor.Descriptor(
  name='moveRequest7',
  full_name='RobotArm.moveRequest7',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='j1', full_name='RobotArm.moveRequest7.j1', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j2', full_name='RobotArm.moveRequest7.j2', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j3', full_name='RobotArm.moveRequest7.j3', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j4', full_name='RobotArm.moveRequest7.j4', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j5', full_name='RobotArm.moveRequest7.j5', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j6', full_name='RobotArm.moveRequest7.j6', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='j7', full_name='RobotArm.moveRequest7.j7', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commandType', full_name='RobotArm.moveRequest7.commandType', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=599,
)


_CURRENTSTATUS = _descriptor.Descriptor(
  name='currentStatus',
  full_name='RobotArm.currentStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='RobotArm.currentStatus.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=632,
)

_ROBOTCONFIGURATION_JOINT.containing_type = _ROBOTCONFIGURATION
_ROBOTCONFIGURATION.fields_by_name['j1'].message_type = _ROBOTCONFIGURATION_JOINT
_ROBOTCONFIGURATION.fields_by_name['j2'].message_type = _ROBOTCONFIGURATION_JOINT
_ROBOTCONFIGURATION.fields_by_name['j3'].message_type = _ROBOTCONFIGURATION_JOINT
_ROBOTCONFIGURATION.fields_by_name['j4'].message_type = _ROBOTCONFIGURATION_JOINT
_ROBOTCONFIGURATION.fields_by_name['j5'].message_type = _ROBOTCONFIGURATION_JOINT
_MOVEREQUEST5.fields_by_name['commandType'].enum_type = _MOVETYPE
_MOVEREQUEST7.fields_by_name['commandType'].enum_type = _MOVETYPE
DESCRIPTOR.message_types_by_name['robotConfiguration'] = _ROBOTCONFIGURATION
DESCRIPTOR.message_types_by_name['moveRequest5'] = _MOVEREQUEST5
DESCRIPTOR.message_types_by_name['moveRequest7'] = _MOVEREQUEST7
DESCRIPTOR.message_types_by_name['currentStatus'] = _CURRENTSTATUS
DESCRIPTOR.enum_types_by_name['MoveType'] = _MOVETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

robotConfiguration = _reflection.GeneratedProtocolMessageType('robotConfiguration', (_message.Message,), {

  'Joint' : _reflection.GeneratedProtocolMessageType('Joint', (_message.Message,), {
    'DESCRIPTOR' : _ROBOTCONFIGURATION_JOINT,
    '__module__' : 'robot_arm_pb2'
    # @@protoc_insertion_point(class_scope:RobotArm.robotConfiguration.Joint)
    })
  ,
  'DESCRIPTOR' : _ROBOTCONFIGURATION,
  '__module__' : 'robot_arm_pb2'
  # @@protoc_insertion_point(class_scope:RobotArm.robotConfiguration)
  })
_sym_db.RegisterMessage(robotConfiguration)
_sym_db.RegisterMessage(robotConfiguration.Joint)

moveRequest5 = _reflection.GeneratedProtocolMessageType('moveRequest5', (_message.Message,), {
  'DESCRIPTOR' : _MOVEREQUEST5,
  '__module__' : 'robot_arm_pb2'
  # @@protoc_insertion_point(class_scope:RobotArm.moveRequest5)
  })
_sym_db.RegisterMessage(moveRequest5)

moveRequest7 = _reflection.GeneratedProtocolMessageType('moveRequest7', (_message.Message,), {
  'DESCRIPTOR' : _MOVEREQUEST7,
  '__module__' : 'robot_arm_pb2'
  # @@protoc_insertion_point(class_scope:RobotArm.moveRequest7)
  })
_sym_db.RegisterMessage(moveRequest7)

currentStatus = _reflection.GeneratedProtocolMessageType('currentStatus', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTSTATUS,
  '__module__' : 'robot_arm_pb2'
  # @@protoc_insertion_point(class_scope:RobotArm.currentStatus)
  })
_sym_db.RegisterMessage(currentStatus)


# @@protoc_insertion_point(module_scope)
